FROM python:3.11

WORKDIR /app

# Install all dependencies with pip (faster and simpler)
RUN pip install --no-cache-dir \
    fastapi>=0.104.0 \
    "uvicorn[standard]>=0.24.0" \
    pydantic>=2.5.0 \
    prometheus-client>=0.19.0 \
    python-jose[cryptography]>=3.3.0 \
    joblib>=1.3.0 \
    pandas>=2.1.0 \
    scikit-learn>=1.3.0 \
    pyyaml>=6.0 \
    python-multipart>=0.0.6 \
    requests>=2.31.0 \
    numpy>=1.24.0 \
    scipy>=1.10.0 \
    boto3>=1.29.0 \
    psycopg2-binary>=2.9.7 \
    sqlalchemy>=2.0.0 \
    python-json-logger>=2.0.0

# Copy application code
COPY app/ ./app/
COPY ml/ ./ml/
RUN touch app/__init__.py ml/__init__.py

EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:8000/health || exit 1

ENV UVICORN_RELOAD=""
CMD ["sh", "-c", "uvicorn app.main:app --host=0.0.0.0 --port=8000 ${UVICORN_RELOAD}"]