replicaCount: 2

image:
  repository: diabetes-mlops
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.diabetes.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: diabetes-tls
      hosts:
        - api.diabetes.yourdomain.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

environment: "production"

mlflow:
  uri: "http://mlflow.mlops.svc.cluster.local:5000"

database:
  url: "postgresql://postgres:postgres@postgres.mlops.svc.cluster.local:5432/mlflow"

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    path: /metrics